load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "jmg",
    srcs = [
        "src/cbe.cpp",
        "src/ip_endpoint.cpp",
        "src/server.cpp",
        "src/system.cpp",
        "src/util.cpp",
    ],
    hdrs = [
        "include/jmg/array_proxy.h",
        "include/jmg/bitwise_scoped_enums.h",
        "include/jmg/cmdline.h",
        "include/jmg/conversion.h",
        "include/jmg/field.h",
        "include/jmg/file_util.h",
        "include/jmg/future.h",
        "include/jmg/ip_endpoint.h",
        "include/jmg/meta.h",
        "include/jmg/object.h",
        "include/jmg/preprocessor.h",
        "include/jmg/random.h",
        "include/jmg/safe_types.h",
        "include/jmg/server.h",
        "include/jmg/system.h",
        "include/jmg/thread_pool.h",
        "include/jmg/types.h",
        "include/jmg/union.h",
        "include/jmg/util.h",
        # jmg language object types below here
        "include/jmg/cbe/cbe.h",
        "include/jmg/protobuf/protobuf.h",
        "include/jmg/ptree/ptree.h",
        "include/jmg/quickfix/quickfix.h",
        "include/jmg/native/native.h",
        "include/jmg/yaml/yaml.h",
    ],
    includes = ["include"],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        "@boost.date_time",
        "@boost.property_tree",
        "@com_google_abseil//absl/container:btree",
        "@com_google_abseil//absl/container:flat_hash_map",
        "@com_google_abseil//absl/container:flat_hash_set",
        "@com_google_abseil//absl/random",
        "@com_google_abseil//absl/strings",
        "@com_google_abseil//absl/time",
        "@ctre",
        "@doom_strong_type//:strong_type",
        "@ericniebler_meta//:meta",
        "@liburing",
        "@more_concepts",
        "@protobuf",
        "@yaml-cpp//:yaml-cpp",
    ],
)

cc_library(
    name = "jmg_server_main",
    srcs = ["src/server_main.cpp"],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [":jmg"],
)
