
cc_binary(
    name = "jmgc",
    visibility = ["//visibility:public"],
    srcs = [
        "jmg_spec.cpp",
        "jmg_spec.h",
        "jmgc.cpp",
        "quickfix_spec.cpp",
        "quickfix_spec.h",
        "spec_util.cpp",
        "spec_util.h",
    ],
    linkstatic = True,
    deps = [
        "//:jmg",
    ],
)
