/** -*- mode: c++ -*-
 *
 * Copyright (C) 2024 Brian Davis
 * All Rights Reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Author: Brian Davis <brian8702@sbcglobal.net>
 *
 */

#include "proto_spec.h"

#include <ranges>
#include <regex>

using namespace jmg;
using namespace std;
using namespace std::string_view_literals;

namespace j2 = jinja2;
namespace vws = std::views;

namespace jmgc
{

string ProtoYamlSpec::tgtFileName() const {
  JMG_ENFORCE_USING(
    logic_error, pred(pkg_),
    "requested target file name before input file was processed");
  return str_cat(snakeCaseToCamelCase(jmg::get<Name>(*pkg_)), ".proto.h");
}

string_view ProtoYamlSpec::encodingHeaderFileName() const {
  return "jmg/protobuf/protobuf.h"sv;
}

string_view ProtoYamlSpec::encodingName() const { return "protobuf"sv; }

void ProtoYamlSpec::processPkg(const YAML::Node& jmg_pkg) {
  JmgYamlSpec::processPkg(jmg_pkg);

  JMG_ENFORCE(
    pred(pkg_),
    "base class processing did not correctly generate a package object");

  // get the namespace used by the generated protobuf code using the declared
  // protobuf package name
  static const auto recognizer = regex(R"(\.)");
  const auto proto_pkg = jmg::try_get<ProtobufPackage>(*pkg_);
  JMG_ENFORCE(pred(proto_pkg),
              "[protobuf_package] field is required in the [package] section "
              "when generating a protobuf encoding wrapper");
  proto_ns = *proto_pkg;
  proto_ns = regex_replace(proto_ns, recognizer, "::");
}

void ProtoYamlSpec::enrichJ2Pkg(jinja2::ValuesMap& j2_pkg,
                                const jmg::PkgDef& pkg_def) const {
  // use source header generated by protoc
  j2::ValuesList src_hdrs;
  src_hdrs.push_back(str_cat(jmg::get<Name>(pkg_def), ".pb.h"sv));
  j2_pkg["src_hdrs"] = std::move(src_hdrs);
}

void ProtoYamlSpec::enrichJ2Obj(jinja2::ValuesMap& j2_obj,
                                const std::string_view obj_name) const {
  // rewrite the JMG object name based on the convention adopted for protobuf objects
  j2_obj["name"] = str_cat(obj_name, "Obj"sv);
  // use the source object generated by protoc
  j2_obj["src_obj"] = str_cat(proto_ns, "::"sv, obj_name);
}

void ProtoYamlSpec::enrichJ2Fld(jinja2::ValuesMap& j2_fld,
                                const ObjGrpFld& fld_def) const {
  {
    const auto type_name = jmg::get<Type>(fld_def);
    if ("array"sv == type_name) {
      // fix up the subtype, if necessary
      const auto sub_type = jmg::try_get<SubType>(fld_def);
      JMG_ENFORCE(pred(sub_type), "no subtype provided for array field [",
                  jmg::get<Name>(fld_def));
      if (obj_def_values_.contains(*sub_type)) {
        j2_fld["subtype"] = str_cat(*sub_type, "Obj");
      }
    }
    else {
      // fix up the type, if necessary
      if (obj_def_values_.contains(type_name)) {
        // use the Obj suffix convention for objects (which should mirror
        // protobuf messages declared in the .proto file
        j2_fld["type"] = str_cat(type_name, "Obj");
      }
    }
  }
  {
    // add the field ID
    const auto id = jmg::try_get<ProtobufId>(fld_def);
    JMG_ENFORCE(pred(id), "no protobuf field ID was provided for field [",
                jmg::get<Name>(fld_def), "]");
    j2_fld["field_id"] = str_cat(*id, "U"sv);
  }
}

void ProtoYamlSpec::enrichJ2Type(jinja2::ValuesMap& j2_type,
                                 const jmg::TypeDef& type_def) const {
  const auto type_name = jmg::get<Type>(type_def);
  if ("enum"sv == type_name) {
    const auto name = jmg::get<Name>(type_def);
    j2_type["alias"] =
      str_cat("using ", name, " = ", proto_ns, "::"sv, name, ";"sv);
  }
}

} // namespace jmgc
