/** -*- mode: c++ -*-
 *
 * Copyright (C) 2024 Brian Davis
 * All Rights Reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Author: Brian Davis <brian8702@sbcglobal.net>
 *
 */

#include "proto_spec.h"

#include <ranges>
#include <regex>

using namespace jmg;
using namespace std;
using namespace std::string_view_literals;

namespace vws = std::views;

namespace jmgc
{

string ProtoYamlSpec::tgtFileName() const {
  JMG_ENFORCE_USING(
    logic_error, pred(pkg_),
    "requested target file name before input file was processed");
  return str_cat(snakeCaseToCamelCase(jmg::get<Name>(*pkg_)), ".proto.h");
}

string_view ProtoYamlSpec::encodingHeaderFileName() const {
  return "jmg/protobuf/protobuf.h"sv;
}

string_view ProtoYamlSpec::encodingNamespace() const {
  return "jmg::protobuf"sv;
}

string_view ProtoYamlSpec::encodingFieldDef() const { return "Field"sv; }

void ProtoYamlSpec::emitEnum(ostream& strm,
                             string_view name,
                             optional<string_view> ul_type,
                             const jmg::Enumerations& enumerations) const {
  // don't emit the enum, which should come from the .proto declaration;
  // instead, add the enriched name to the extra translations
  emplace_uniq("extra type translations"sv, extraTranslations_, string(name),
               str_cat(proto_ns, "::", name));
}

void ProtoYamlSpec::enrichFld(ostream& strm, const ObjGrpFld& fld_def) const {
  const auto id = jmg::try_get<ProtobufId>(fld_def);
  JMG_ENFORCE(pred(id), "no protobuf field ID was provided for field [",
              jmg::get<Name>(fld_def), "]");
  strm << ", " << *id << "U";
}

void ProtoYamlSpec::emitPkg(ostream& strm, const jmg::PkgDef& pkg_def) const {
  // get the namespace used by the generated protobuf code using the declared
  // protobuf package name
  static const auto recognizer = regex(R"(\.)");
  const auto proto_pkg = jmg::try_get<ProtobufPackage>(pkg_def);
  JMG_ENFORCE(pred(proto_pkg),
              "[protobuf_package] field is required in the [package] section "
              "when generating a protobuf encoding wrapper");
  proto_ns = *proto_pkg;
  proto_ns = regex_replace(proto_ns, recognizer, "::");

  // automatically include the header file generated by protoc in the header
  // file generated for the wrapper
  strm << "#include \"" << jmg::get<Name>(pkg_def) << ".pb.h\"\n\n";

  Base::emitPkg(strm, pkg_def);
}

void ProtoYamlSpec::emitObj(ostream& strm,
                            const string_view name,
                            const JmgObjGrpFlds& flds) const {
  const auto encoding_name = str_cat(name, "Obj");
  strm << "\nusing " << encoding_name << " = " << "jmg::protobuf::Object<"
       << proto_ns << "::" << name << ",\n  ";
  const auto flds_view =
    flds | vws::transform([&](const auto& fld) {
      return snakeCaseToCamelCase(jmg::get<Name>(*fld),
                                  true /* capitalize_leading */);
    });
  strm << str_join(flds_view, ",\n  ");
  strm << ">;\n";

  // add translation from protobuf generated class name to the JMG object that
  // wraps it
  emplace_uniq("extra type translations"sv, extraTranslations_, string(name),
               str_cat(name, "Obj"));
}

} // namespace jmgc
