/** -*- mode: c++ -*-
 *
 * Copyright (C) 2024 Brian Davis
 * All Rights Reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Author: Brian Davis <brian8702@sbcglobal.net>
 *
 */

/**
 * test cases for encoding implementations generated by jmgc
 *
 * this code is structured as follows:
 *
 * 1. there is a single .yaml file with all of the JMG language
 *    definitions
 *
 * 2. the BUILD file has a target for each encoding type that combines
 *    this code with the output of building the encoding
 *    implementation and a support file specific to the foreign
 *    encoding type which builds objects with known values that are
 *    then converted to JMG objects and subjected to test cases
 */

#include "test_jmgc_any.h"

#include "jmg/util.h"

namespace jmg::test_jmgc
{

// constants used for TestValues

// strings
const std::string TestValues::kStr = std::string("foo");
const std::string TestValues::kBytesStr = std::string("bar");
// safe int
const IntId TestValues::kIntId = IntId(static_cast<uint32_t>(1337));
// NOTE: using integer value here because the symbol names of the
// enumerations are different between encoding implementations, but
// the enumeration values are all the same
const Active TestValues::kActiveState = Active(static_cast<uint8_t>(2));
// arrays
const std::array<std::string, 3> TestValues::kStrs = {std::string("foo"),
                                                      std::string("bar"),
                                                      std::string("blub")};
const std::array<std::optional<std::string>, 2> TestValues::kInnerOptStrs = {
  std::nullopt, std::string("blub")};

} // namespace jmg::test_jmgc

#include <gmock/gmock.h>
#include <google/protobuf/message.h>

using namespace jmg;
using namespace jmg::test_jmgc;
using namespace std;

namespace rng = std::ranges;
namespace vws = std::views;

class TestJmgcAny : public ::testing::Test, public TestValues {
protected:
  static void SetUpTestSuite() {
    tp_ = getCurrentTime();

    ////////////////////
    // initialize msg
    non_jmg_test_msg_ = makeNonJmgTestMsg(tp_);
  }

  static TimePoint tp_;
  static NonJmgTestMsg non_jmg_test_msg_;
};

TimePoint TestJmgcAny::tp_;
NonJmgTestMsg TestJmgcAny::non_jmg_test_msg_;

TEST_F(TestJmgcAny, TestGet) {
  const auto obj = JmgTestMsg(non_jmg_test_msg_);

  // boolean
  EXPECT_EQ(kBoolean, jmg::get<Boolean>(obj));
  // 32 bit integers
  EXPECT_EQ(kInt32, jmg::get<Int32>(obj));
  EXPECT_EQ(kUInt32, jmg::get<Uint32>(obj));
  EXPECT_EQ(kSFixed32, jmg::get<Sfixed32>(obj));
  EXPECT_EQ(kFixed32, jmg::get<Fixed32>(obj));
  // 64 bit integers
  EXPECT_EQ(kInt64, jmg::get<Int64>(obj));
  EXPECT_EQ(kUInt64, jmg::get<Uint64>(obj));
  EXPECT_EQ(kSFixed64, jmg::get<Sfixed64>(obj));
  EXPECT_EQ(kFixed64, jmg::get<Fixed64>(obj));
  // floating point
  EXPECT_EQ(kFlt, jmg::get<Flt>(obj));
  EXPECT_EQ(kDbl, jmg::get<Dbl>(obj));
  // strings
  EXPECT_EQ(kStr, jmg::get<Str>(obj));
  EXPECT_EQ(kBytesStr, jmg::get<BytesStr>(obj));
  // time point
  EXPECT_EQ(tp_, jmg::get<TimeStamp>(obj));
  // safe integer ID
  EXPECT_EQ(kIntId, jmg::get<IntIdFld>(obj));
  // enum value
  EXPECT_EQ(kActiveState, jmg::get<ActiveState>(obj));

  ////////////////////
  // arrays

  // primitive array
  const auto ints = jmg::get<Ints>(obj);
  EXPECT_TRUE(rng::range<decltype(ints)>);
  EXPECT_EQ(kInts.size(), ints.size());
  for (const auto [idx, entry] : vws::enumerate(ints)) {
    EXPECT_EQ(kInts.at(idx), entry);
  }
  // string array
  const auto strs = jmg::get<Strs>(obj);
  EXPECT_EQ(3, strs.size());
  EXPECT_TRUE(rng::range<decltype(strs)>);
  for (const auto [expected, actual] : vws::zip(kStrs, strs)) {
    EXPECT_EQ(string_view(expected), static_cast<string>(actual));
  }
  // object array
  const auto inner_msgs = jmg::get<InnerMsgs>(obj);
  EXPECT_EQ(2, inner_msgs.size());
  EXPECT_TRUE(rng::range<decltype(inner_msgs)>);
  for (const auto& [idx, inner_msg] : vws::enumerate(inner_msgs)) {
    EXPECT_EQ(kInnerInts[idx], jmg::get<InnerInt32>(inner_msg));
    const auto opt_str = jmg::try_get<OptInnerStr>(inner_msg);
    // TODO(bd) should this check have the YAML case explicitly separated?
    // NOTE: yaml-cpp is stingy with its internal representation and strings are
    // returned by value
    EXPECT_TRUE(StdStringLikeT<RemoveOptionalT<decltype(opt_str)>>);
    EXPECT_EQ(pred(kInnerOptStrs[idx]), pred(opt_str));
    if (opt_str) { EXPECT_EQ(*(kInnerOptStrs[idx]), *opt_str); }
  }
}

#define JMG_VALIDATE_OPT_FLD(test_obj, opt_fld, test_val) \
  do {                                                    \
    const auto empty = jmg::try_get<opt_fld>(test_obj);   \
    EXPECT_FALSE(pred(empty));                            \
    jmg::set<opt_fld>(test_obj, test_val);                \
    const auto opt_val = jmg::try_get<opt_fld>(test_obj); \
    EXPECT_TRUE(pred(opt_val));                           \
    EXPECT_EQ(test_val, *opt_val);                        \
  } while (0)

TEST_F(TestJmgcAny, TestSetAndTryGet) {
  NonJmgTestOptMsg msg;
  auto obj = JmgTestOptMsg(msg);
  // boolean
  JMG_VALIDATE_OPT_FLD(obj, OptBool, kBoolean);
  // 32 bit integers
  JMG_VALIDATE_OPT_FLD(obj, OptInt32, kInt32);
  JMG_VALIDATE_OPT_FLD(obj, OptUint32, kUInt32);
  JMG_VALIDATE_OPT_FLD(obj, OptSfixed32, kSFixed32);
  JMG_VALIDATE_OPT_FLD(obj, OptFixed32, kFixed32);
  // 64 bit integers
  JMG_VALIDATE_OPT_FLD(obj, OptInt64, kInt64);
  JMG_VALIDATE_OPT_FLD(obj, OptUint64, kUInt64);
  JMG_VALIDATE_OPT_FLD(obj, OptSfixed64, kSFixed64);
  JMG_VALIDATE_OPT_FLD(obj, OptFixed64, kFixed64);
  // floating point
  JMG_VALIDATE_OPT_FLD(obj, OptFlt, kFlt);
  JMG_VALIDATE_OPT_FLD(obj, OptDbl, kDbl);
  // strings
  JMG_VALIDATE_OPT_FLD(obj, OptStr, kStr);
  JMG_VALIDATE_OPT_FLD(obj, OptBytesStr, kBytesStr);
  // time point
  JMG_VALIDATE_OPT_FLD(obj, OptTimeStamp, tp_);
  // safe integer ID
  JMG_VALIDATE_OPT_FLD(obj, OptIntIdFld, kIntId);
  // enum
  JMG_VALIDATE_OPT_FLD(obj, OptActiveState, kActiveState);
}

#undef JMG_VALIDATE_OPT_FLD
