/** -*- mode: c++ -*-
 *
 * Copyright (C) 2026 Brian Davis
 * All Rights Reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Author: Brian Davis <brian8702@sbcglobal.net>
 *
 */
#pragma once

#if defined(JMG_TEST_CBE)
#error "attempting to test both protobuf and cbe"
#endif
#if defined(JMG_TEST_YAML)
#error "attempting to test both protobuf and yaml"
#endif

// NOTE: header generated by jmgc
#include "test_jmgc.proto.h"

namespace jmg::test_jmgc
{

template<typename T, jmg::StrLiteral kName, jmg::TypeFlagT IsRequired, uint32_t kFldId>
using FldDefType = jmg::protobuf::Field<T, kName, IsRequired, kFldId>;

template<jmg::StrLiteral kName, jmg::TypeFlagT IsRequired, uint32_t kFldId>
using StrFldDefType = jmg::protobuf::StringField<kName, IsRequired, kFldId>;

template<typename T, jmg::StrLiteral kName, jmg::TypeFlagT IsRequired, uint32_t kFldId>
using ArrayDefType = jmg::protobuf::ArrayField<T, kName, IsRequired, kFldId>;

template<typename T, typename... Ts>
using ObjDefType = jmg::protobuf::Object<T, Ts...>;

using NonJmgTestMsg = jmgc::test::TestMsg;
using JmgTestMsg = TestMsgObj;

NonJmgTestMsg makeNonJmgTestMsg(const jmg::TimePoint tp);

using NonJmgTestOptMsg = jmgc::test::TestOptMsg;
using JmgTestOptMsg = TestOptMsgObj;

} // namespace jmg::test_jmgc

using namespace jmg::protobuf;
// NOTE: the jmgc::test namespace is required by the package definition in the
// .proto file generated by jmgc
using namespace jmgc::test;
